#!/bin/bash

PROJECT=`php -r "echo dirname(dirname(realpath('$0')));"`
STAGED_FILES_CMD=`git diff --cached --name-only --diff-filter=ACMR HEAD | grep \\\\.php`

echo "$PROJECT"

# Determine if a file list is passed
if [ "$#" -eq 1 ]
then
    oIFS=$IFS
    IFS='
    '
    SFILES="$1"
    IFS=$oIFS
fi
SFILES=${SFILES:-$STAGED_FILES_CMD}

echo "Checking PHPCS..."
for FILE in $SFILES
do
    php -l -d display_errors=0 "$PROJECT/$FILE"
    if [ $? != 0 ]
    then
        echo "Fix the error before commit."
        exit 1
    fi
    FILES="$FILES \"$PROJECT/$FILE\""
done

if [ -f "$PROJECT/phpcs.xml" ]
then
    RULESET="$PROJECT/phpcs.xml"
else
    RULESET="WordPress"
fi

echo "Checking Code Standard Compliance, using $RULESET as ruleset standard..."
for FILE in $SFILES
do
    composer phpcs --colors --encoding=utf-8 -n -p "$PROJECT/$FILE"
    if [ $? != 0 ]
    then
        echo "Fix the error before commit."
        echo "Run"
        echo "composer phpcs $FILES"
        echo "for automatic fix or fix it manually."
        exit 1
    fi
done

exit $?