---
##############################################################
# Vars in vault:
# rds_master_user     = master user for database
# rds_master_password = password for master user
##############################################################

##############################################################
# database_server_type = server type (base or rds)
##############################################################
database_server_type: base

##############################################################
# mysql_packages = Packages to install with apt-get
#
# Typically this is only needed for non-rds database setups
# meaning development
##############################################################
# mysql_packages:
#   - mariadb-client
#   - mariadb-server
#   - python-mysqldb