#!/usr/bin/env bash
#
# Prefixes commit messages [JIRA_TICKET] the commit message based on a branch format of
# feature|bugfix/<ticket>/<branch_description>
#

FILE=$1
MESSAGE=$(cat $FILE)
IFS=/ read -a parts <<< $(git rev-parse --abbrev-ref HEAD)
TICKET=[$(echo ${parts[1]} | grep -Eo '(\w+[-])?[0-9]+')]
if [[ $TICKET == "[]" || "$MESSAGE" == "$TICKET"* ]]; then
  exit 0
fi
echo "$TICKET $MESSAGE" > $FILE
