/**
 *
 * Module: grunt-contrib-concat
 * Documentation: https://npmjs.org/package/grunt-contrib-concat
 *
 */

module.exports = {

	libs: {
		options: {
			banner:
				'/**\n' +
				'  *\n' +
				'  * Square One: JS Libs\n' +
				'  *\n' +
				'  * @since <%= pkg.version %> built on <%= grunt.template.today("mm-dd-yyyy") %>\n' +
				'  *\n' +
				'  * DO NOT EDIT THIS JS FILE DIRECTLY. IT IS GENERATED BY GRUNT.\n' +
				'  * -------------------------------------------------------------\n' +
				'  * See the js directory and edit the source files in the "libs"\n' +
				'  * directory of this folder.\n' +
				'  *\n' +
				'  */\n\n'
		},
		src: [
			'<%= pkg._componentpath %>/js/sprintf.js',
			'<%= pkg._componentpath %>/js/modernizr.tests.js',
			'<%= pkg._componentpath %>/js/custom.js',

			'<%= pkg._bowerpath %>/jquery-ui/ui/jquery.ui.core.js',
			'<%= pkg._bowerpath %>/jquery-ui/ui/jquery.ui.effect.js',

			'<%= pkg._bowerpath %>/lodash/dist/lodash.compat.js',
			'<%= pkg._bowerpath %>/underscore.string/lib/underscore.string.js',

			'<%= pkg._bowerpath %>/fastclick/lib/fastclick.js',

			'<%= pkg._bowerpath %>/handlebars/handlebars.runtime.js',
			'<%= pkg._bowerpath %>/verge/verge.js',

			'dev/node_modules/babel/node_modules/babel-core/browser-polyfill.js.js',

			'<%= pkg._themepath %>/js/libs/*.js'
		],
		dest: '<%= pkg._themepath %>/js/libs.js'
	},

	handlebars: {
		options: {
			banner:
				'/**\n' +
				'  *\n' +
				'  * Square One: JS Templates\n' +
				'  *\n' +
				'  * @since <%= pkg.version %> built on <%= grunt.template.today("mm-dd-yyyy") %>\n' +
				'  *\n' +
				'  * DO NOT EDIT THIS JS FILE DIRECTLY. IT IS GENERATED BY GRUNT.\n' +
				'  * -------------------------------------------------------------\n' +
				'  * See the js directory and edit the source files in the "templates"\n' +
				'  * directory of this folder.\n' +
				'  *\n' +
				'  */\n\n'
		},
		src: [
			'<%= pkg._themepath %>/js/templates.js',
			'<%= pkg._themepath %>/js/helpers/*.js'

		],
		dest: '<%= pkg._themepath %>/js/templates.js'
	},

	scripts: {
		options: {
			banner: 
				'/**\n' +
				'  *\n' +
				'  * Square One: JS Scripts\n' +
				'  *\n' +
				'  * @namespace modern_tribe\n' +
				'  *\n' +
				'  * @since <%= pkg.version %> built on <%= grunt.template.today("mm-dd-yyyy") %>\n' +
				'  * @desc The modern_tribe namespace stores all custom functions, data, application states\n' +
				'  * and an empty events object to bind custom events to.\n' +
				'  * It is aliased to the letter "t" in the code below for the sake of brevity.\n' +
				'  * modern_tribe_i18n is aliased to nls and contains all language strings.\n' +
				'  * modern_tribe_config is aliased to config and contains all config info required by js from wp.\n' +
				'  *\n' +
				'  * DO NOT EDIT THIS JS FILE DIRECTLY. IT IS GENERATED BY GRUNT.\n' +
				'  * -------------------------------------------------------------\n' +
				'  * See the js directory and edit the source files in the "scripts"\n' +
				'  * directory of this folder.\n' +
				'  *\n' +
				'  */\n\n' +
				'var modern_tribe = window.modern_tribe || {};\n\n' +
				'(function (window, document, $, t, nls, config, m) {\n\n',
			footer: '\n\n})(window, document, jQuery, modern_tribe, modern_tribe_i18n, modern_tribe_config, Modernizr);'
		},
		src: [
			'<%= pkg._themepath %>/js/scripts/plugins.js',
			'<%= pkg._themepath %>/js/scripts/browser.js',
			'<%= pkg._themepath %>/js/scripts/data.js',
			'<%= pkg._themepath %>/js/scripts/elements.js',
			'<%= pkg._themepath %>/js/scripts/keys.js',
			'<%= pkg._themepath %>/js/scripts/namespaces.js',
			'<%= pkg._themepath %>/js/scripts/modules/**/*.js',
			'!<%= pkg._themepath %>/js/scripts/modules/example.js',
			'<%= pkg._themepath %>/js/scripts/options.js',
			'<%= pkg._themepath %>/js/scripts/state.js',
			'<%= pkg._themepath %>/js/scripts/tests.js',
			'<%= pkg._themepath %>/js/scripts/init.js'
		],
		dest: '<%= pkg._themepath %>/js/scripts-es6.js'
	}

};