#!/bin/bash
# script/cibuild: Setup environment for CI build, tests and prepare for a deploy.
#                 This is primarily designed to run on the continuous integration server.

SCRIPTDIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

# Source configuration files
source ${SCRIPTDIR}/local.ini

cd ${PARENTDIR}

usage(){
	echo "Usage: $0 [composer|node]"
	exit 1
}

# Install Composer
build_composer() {
    composer install --ignore-platform-reqs --no-dev --optimize-autoloader
}

# Build node
build_node() {
    echo "Building Node"
    npm install node-gyp
    npm install gulp-cli -g
    npm run install:theme
    npm run validate
    npm run server_dist
}

while true; do
    case "$1" in
        composer)
            build_composer
            shift
            break
            ;;
        node)
            build_node
            shift
            break
            ;;
        --)
            usage
            shift
            break
            ;;
        *)
            build_composer
            build_node
            break
            ;;
    esac
done
