#!/bin/bash
# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

SCRIPTDIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

# Source configuration files
source ${SCRIPTDIR}/local.ini

cd "$SCRIPTDIR";

# Create config folder
if [ ! -d ${CONFIG_FOLDER} ]; then
    mkdir -p ${CONFIG_FOLDER}
    echo "*.key" >> ${CONFIG_FOLDER}/.gitignore
    echo "temp/*" >> ${CONFIG_FOLDER}/.gitignore
fi

# echo "Creating private keys"
ssh-keygen -t rsa -b 4096 -q -P "" -f ${CERT_FILE} -C "${PARENTDIR_NAME}"

echo ""
echo "Now add the ${PARENTDIR_NAME}.pub to your servers so the CI system can properly deploy. "
echo "Setup complete. Edit the ${WPENGINE_FOLDER}/config.ini and you're ready to go."