---
- name: Application Deploy
  hosts: www
  roles:
    - role: tribe/roles/project-fetch
      deploy_project: wordpress
      tags:
        - fetch

    - role: tribe/roles/build
      deploy_project: wordpress
      tags:
        - build

    - role: tribe/roles/project-activate
      deploy_project: wordpress
      tags:
        - activate

    - role: tribe/roles/cleanup
      tags:
        - cleanup