---
- name: Project setup
  hosts: www
  roles:
    - role: tribe/roles/project-directory
      deploy_project: wordpress
      tags:
        - directory

    - role: tribe/roles/project-fetch
      deploy_project: wordpress
      tags:
        - fetch

    - role: tribe/roles/grunt
      deploy_project: wordpress
      tags:
        - grunt

    - role: tribe/roles/wpcli
      become: yes
      tags:
        - wpcli
        - wordpress

    - role: tribe/roles/build
      deploy_project: wordpress
      tags:
        - build

    - role: tribe/roles/project-activate
      deploy_project: wordpress
      tags:
        - activate

    - role: tribe/roles/wordpress
      become: yes
      tags:
        - wordpress

    - role: tribe/roles/cleanup
      tags:
        - cleanup